runtime: python27
api_version: 1
threadsafe: true
service: portofolio
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 2

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)